package RatingRulesLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum RoundingMethodOptionsEnum {
  AlwaysTowardsZero("AlwaysTowardsZero", "AlwaysTowardsZero"),
  RoundUp("RoundUp", "RoundUp"),
  RoundDown("RoundDown", "RoundDown"),
  RoundBasedOnReminder("RoundBasedOnReminder", "RoundBaseOnReminder");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private RoundingMethodOptionsEnum(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<RoundingMethodOptionsEnum> getConstants() {
    List<RoundingMethodOptionsEnum> list = ListSequence.fromList(new LinkedList<RoundingMethodOptionsEnum>());
    ListSequence.fromList(list).addElement(RoundingMethodOptionsEnum.AlwaysTowardsZero);
    ListSequence.fromList(list).addElement(RoundingMethodOptionsEnum.RoundUp);
    ListSequence.fromList(list).addElement(RoundingMethodOptionsEnum.RoundDown);
    ListSequence.fromList(list).addElement(RoundingMethodOptionsEnum.RoundBasedOnReminder);
    return list;
  }
  public static RoundingMethodOptionsEnum getDefault() {
    return RoundingMethodOptionsEnum.AlwaysTowardsZero;
  }
  public static RoundingMethodOptionsEnum parseValue(String value) {
    if (value == null) {
      return RoundingMethodOptionsEnum.getDefault();
    }
    if (value.equals(RoundingMethodOptionsEnum.AlwaysTowardsZero.getValueAsString())) {
      return RoundingMethodOptionsEnum.AlwaysTowardsZero;
    }
    if (value.equals(RoundingMethodOptionsEnum.RoundUp.getValueAsString())) {
      return RoundingMethodOptionsEnum.RoundUp;
    }
    if (value.equals(RoundingMethodOptionsEnum.RoundDown.getValueAsString())) {
      return RoundingMethodOptionsEnum.RoundDown;
    }
    if (value.equals(RoundingMethodOptionsEnum.RoundBasedOnReminder.getValueAsString())) {
      return RoundingMethodOptionsEnum.RoundBasedOnReminder;
    }
    return RoundingMethodOptionsEnum.getDefault();
  }
}
