package RatingRulesLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;

public class startTime_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    String testValue = null;
    if (value == null) {
      testValue = "";
    } else {
      testValue = value;
    }
    return testValue.matches("^(?:(?:([01]?\\d|2[0-3]):)?([0-5]?\\d):)?([0-5]?\\d)$");
  }
}
