package RatingRulesLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum TapTypeEnum {
  TapOn("TapOn", "TapOn"),
  TapOff("TapOff", "TapOff");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private TapTypeEnum(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<TapTypeEnum> getConstants() {
    List<TapTypeEnum> list = ListSequence.fromList(new LinkedList<TapTypeEnum>());
    ListSequence.fromList(list).addElement(TapTypeEnum.TapOn);
    ListSequence.fromList(list).addElement(TapTypeEnum.TapOff);
    return list;
  }
  public static TapTypeEnum getDefault() {
    return TapTypeEnum.TapOn;
  }
  public static TapTypeEnum parseValue(String value) {
    if (value == null) {
      return TapTypeEnum.getDefault();
    }
    if (value.equals(TapTypeEnum.TapOn.getValueAsString())) {
      return TapTypeEnum.TapOn;
    }
    if (value.equals(TapTypeEnum.TapOff.getValueAsString())) {
      return TapTypeEnum.TapOff;
    }
    return TapTypeEnum.getDefault();
  }
}
