package RatingRulesLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum ValidationTapDateEnum {
  TapOnDate("TapOnDate", "TapOnDate"),
  TapOffDate("TapOffDate", "TapOffDate");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private ValidationTapDateEnum(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<ValidationTapDateEnum> getConstants() {
    List<ValidationTapDateEnum> list = ListSequence.fromList(new LinkedList<ValidationTapDateEnum>());
    ListSequence.fromList(list).addElement(ValidationTapDateEnum.TapOnDate);
    ListSequence.fromList(list).addElement(ValidationTapDateEnum.TapOffDate);
    return list;
  }
  public static ValidationTapDateEnum getDefault() {
    return ValidationTapDateEnum.TapOnDate;
  }
  public static ValidationTapDateEnum parseValue(String value) {
    if (value == null) {
      return ValidationTapDateEnum.getDefault();
    }
    if (value.equals(ValidationTapDateEnum.TapOnDate.getValueAsString())) {
      return ValidationTapDateEnum.TapOnDate;
    }
    if (value.equals(ValidationTapDateEnum.TapOffDate.getValueAsString())) {
      return ValidationTapDateEnum.TapOffDate;
    }
    return ValidationTapDateEnum.getDefault();
  }
}
