package RatingRulesLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum WeekDaysEnum {
  _1("Monday", 1),
  _2("Tuesday", 2),
  _3("Wednesday", 3),
  _4("Thursday", 4),
  _5("Friday", 5),
  _6("Saturday", 6),
  _7("Sunday", 7);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  WeekDaysEnum(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<WeekDaysEnum> getConstants() {
    List<WeekDaysEnum> list = ListSequence.fromList(new LinkedList<WeekDaysEnum>());
    ListSequence.fromList(list).addElement(WeekDaysEnum._1);
    ListSequence.fromList(list).addElement(WeekDaysEnum._2);
    ListSequence.fromList(list).addElement(WeekDaysEnum._3);
    ListSequence.fromList(list).addElement(WeekDaysEnum._4);
    ListSequence.fromList(list).addElement(WeekDaysEnum._5);
    ListSequence.fromList(list).addElement(WeekDaysEnum._6);
    ListSequence.fromList(list).addElement(WeekDaysEnum._7);
    return list;
  }
  public static WeekDaysEnum getDefault() {
    return WeekDaysEnum._1;
  }
  public static WeekDaysEnum parseValue(String value) {
    if (value == null) {
      return WeekDaysEnum.getDefault();
    }
    if (value.equals(WeekDaysEnum._1.getValueAsString())) {
      return WeekDaysEnum._1;
    }
    if (value.equals(WeekDaysEnum._2.getValueAsString())) {
      return WeekDaysEnum._2;
    }
    if (value.equals(WeekDaysEnum._3.getValueAsString())) {
      return WeekDaysEnum._3;
    }
    if (value.equals(WeekDaysEnum._4.getValueAsString())) {
      return WeekDaysEnum._4;
    }
    if (value.equals(WeekDaysEnum._5.getValueAsString())) {
      return WeekDaysEnum._5;
    }
    if (value.equals(WeekDaysEnum._6.getValueAsString())) {
      return WeekDaysEnum._6;
    }
    if (value.equals(WeekDaysEnum._7.getValueAsString())) {
      return WeekDaysEnum._7;
    }
    return WeekDaysEnum.getDefault();
  }
}
