package RatingRulesLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db56f48L, "RatingRulesLanguage.structure.Actions"))) {
        return Collections.<ConceptEditor>singletonList(new Actions_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x1b499c0ca9c50b10L, "RatingRulesLanguage.structure.And"))) {
        return Collections.<ConceptEditor>singletonList(new And_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x7627b8e69a9fd55dL, "RatingRulesLanguage.structure.AndNL"))) {
        return Collections.<ConceptEditor>singletonList(new AndNL_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db713abL, "RatingRulesLanguage.structure.AssignmentOperator"))) {
        return Collections.<ConceptEditor>singletonList(new AssignmentOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db5731eL, "RatingRulesLanguage.structure.BaseAssignmentOperator"))) {
        return Collections.<ConceptEditor>singletonList(new BaseAssignmentOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x6773d363de929589L, "RatingRulesLanguage.structure.BaseAttributeType"))) {
        return Collections.<ConceptEditor>singletonList(new BaseAttributeType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db56f56L, "RatingRulesLanguage.structure.BaseNumericFunctionDef"))) {
        return Collections.<ConceptEditor>singletonList(new BaseNumericFunctionDef_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db57316L, "RatingRulesLanguage.structure.BaseOperator"))) {
        return Collections.<ConceptEditor>singletonList(new BaseOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x6773d363de929654L, "RatingRulesLanguage.structure.BaseProductDataType"))) {
        return Collections.<ConceptEditor>singletonList(new BaseProductDataType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x30491a7e2aa64333L, "RatingRulesLanguage.structure.BaseUnaryOperator"))) {
        return Collections.<ConceptEditor>singletonList(new BaseUnaryOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x4be494590ea1a73cL, "RatingRulesLanguage.structure.BooleanType"))) {
        return Collections.<ConceptEditor>singletonList(new BooleanType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x7627b8e69aaa7fe3L, "RatingRulesLanguage.structure.ConcessionSelectionCriteriaDef"))) {
        return Collections.<ConceptEditor>singletonList(new ConcessionSelectionCriteriaDef_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x7627b8e69aab7381L, "RatingRulesLanguage.structure.ConcessionSelectionCriterias"))) {
        return Collections.<ConceptEditor>singletonList(new ConcessionSelectionCriterias_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x4be494590ea7fdedL, "RatingRulesLanguage.structure.ConcessionType"))) {
        return Collections.<ConceptEditor>singletonList(new ConcessionType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2db09a3bL, "RatingRulesLanguage.structure.Concessions"))) {
        return Collections.<ConceptEditor>singletonList(new Concessions_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x59a528db6b3d9dfaL, "RatingRulesLanguage.structure.ConstantFloatValue"))) {
        return Collections.<ConceptEditor>singletonList(new ConstantFloatValue_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x59a528db6b5b5e5fL, "RatingRulesLanguage.structure.ConstantFloatVarDeclaration"))) {
        return Collections.<ConceptEditor>singletonList(new ConstantFloatVarDeclaration_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db57cabL, "RatingRulesLanguage.structure.ConstantPointToPointFareMatrixValue"))) {
        return Collections.<ConceptEditor>singletonList(new ConstantPointToPointFareMatrixValue_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x59a528db6b5b5e60L, "RatingRulesLanguage.structure.ConstantPointToPointVarDeclaration"))) {
        return Collections.<ConceptEditor>singletonList(new ConstantPointToPointVarDeclaration_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x59a528db6b5188cfL, "RatingRulesLanguage.structure.ConstantTypedVarDeclaration"))) {
        return Collections.<ConceptEditor>singletonList(new ConstantTypedVarDeclaration_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x59a528db6b5188c6L, "RatingRulesLanguage.structure.ConstantVarDeclaration"))) {
        return Collections.<ConceptEditor>singletonList(new ConstantVarDeclaration_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x59a528db6b5188d7L, "RatingRulesLanguage.structure.ConstantVarReference"))) {
        return Collections.<ConceptEditor>singletonList(new ConstantVarReference_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x59a528db6b3d9e81L, "RatingRulesLanguage.structure.ConstantsDeclarationBlock"))) {
        return Collections.<ConceptEditor>singletonList(new ConstantsDeclarationBlock_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db571ffL, "RatingRulesLanguage.structure.CreateTransferProductAction"))) {
        return Collections.<ConceptEditor>singletonList(new CreateTransferProductAction_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x7627b8e69aaa7ff1L, "RatingRulesLanguage.structure.CrtAgeVerificationCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new CrtAgeVerificationCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x26299216448414fdL, "RatingRulesLanguage.structure.CrtEPurseGreatesThanValueCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new CrtEPurseGreatesThanValueCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x7627b8e69aaa8105L, "RatingRulesLanguage.structure.CrtLifespanValidationCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new CrtLifespanValidationCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x6bab076002ecdcd7L, "RatingRulesLanguage.structure.CrtLocationEqualsCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new CrtLocationEqualsCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x6bab076002ecdc69L, "RatingRulesLanguage.structure.CrtMOTEqualsCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new CrtMOTEqualsCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x6bab076002ecdcdbL, "RatingRulesLanguage.structure.CrtRouteEqualsCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new CrtRouteEqualsCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x6bab076002ecdcdcL, "RatingRulesLanguage.structure.CrtServiceProviderEqualsCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new CrtServiceProviderEqualsCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x318d55e0b57640f7L, "RatingRulesLanguage.structure.CrtTapIsOfTypeCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new CrtTapIsOfTypeCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x318d55e0b5764015L, "RatingRulesLanguage.structure.CrtTapTransferCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new CrtTapTransferCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x3c32a02796cf0ff5L, "RatingRulesLanguage.structure.DivisionNLOperator"))) {
        return Collections.<ConceptEditor>singletonList(new DivisionNLOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x3c32a02796cf0ff4L, "RatingRulesLanguage.structure.DivisionOperator"))) {
        return Collections.<ConceptEditor>singletonList(new DivisionOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x59a528db6b51d421L, "RatingRulesLanguage.structure.ElementVarType"))) {
        return Collections.<ConceptEditor>singletonList(new ElementVarType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x6773d363de94c3dbL, "RatingRulesLanguage.structure.FareRuleDefinition"))) {
        return Collections.<ConceptEditor>singletonList(new FareRuleDefinition_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x28b62f6a4de37320L, "RatingRulesLanguage.structure.FareRuleType"))) {
        return Collections.<ConceptEditor>singletonList(new FareRuleType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db56f30L, "RatingRulesLanguage.structure.FareRulesDefinitionBlock"))) {
        return Collections.<ConceptEditor>singletonList(new FareRulesDefinitionBlock_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x59a528db6b5188d6L, "RatingRulesLanguage.structure.FloatVarType"))) {
        return Collections.<ConceptEditor>singletonList(new FloatVarType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db56f45L, "RatingRulesLanguage.structure.GenerateTransactionAction"))) {
        return Collections.<ConceptEditor>singletonList(new GenerateTransactionAction_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x30491a7e2b03d0faL, "RatingRulesLanguage.structure.IntType"))) {
        return Collections.<ConceptEditor>singletonList(new IntType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db571bfL, "RatingRulesLanguage.structure.LValue"))) {
        return Collections.<ConceptEditor>singletonList(new LValue_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x7627b8e69aaa81ffL, "RatingRulesLanguage.structure.LimitedPassbackCheckCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new LimitedPassbackCheckCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da04dbbL, "RatingRulesLanguage.structure.LocationGroupCriteras"))) {
        return Collections.<ConceptEditor>singletonList(new LocationGroupCriteras_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da04d7bL, "RatingRulesLanguage.structure.LocationGroupCriteriaDef"))) {
        return Collections.<ConceptEditor>singletonList(new LocationGroupCriteriaDef_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2db0f562L, "RatingRulesLanguage.structure.LocationReference"))) {
        return Collections.<ConceptEditor>singletonList(new LocationReference_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x4be494590ea1cb9dL, "RatingRulesLanguage.structure.LocationType"))) {
        return Collections.<ConceptEditor>singletonList(new LocationType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2db09c6eL, "RatingRulesLanguage.structure.Locations"))) {
        return Collections.<ConceptEditor>singletonList(new Locations_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x1b499c0ca9c45ca0L, "RatingRulesLanguage.structure.LogicalExpression"))) {
        return Collections.<ConceptEditor>singletonList(new LogicalExpression_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x1b499c0ca9c45ca1L, "RatingRulesLanguage.structure.LogicalOperator"))) {
        return Collections.<ConceptEditor>singletonList(new LogicalOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da13faaL, "RatingRulesLanguage.structure.MOTReference"))) {
        return Collections.<ConceptEditor>singletonList(new MOTReference_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x4be494590ea305b1L, "RatingRulesLanguage.structure.MOTType"))) {
        return Collections.<ConceptEditor>singletonList(new MOTType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x318d55e0b5764104L, "RatingRulesLanguage.structure.MediaTypeEqualsCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new MediaTypeEqualsCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x3c32a02796cf0fb8L, "RatingRulesLanguage.structure.MinusNLOperator"))) {
        return Collections.<ConceptEditor>singletonList(new MinusNLOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x3c32a02796cf0f82L, "RatingRulesLanguage.structure.MinusOperator"))) {
        return Collections.<ConceptEditor>singletonList(new MinusOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2d9f2e1aL, "RatingRulesLanguage.structure.ModesOfTransportation"))) {
        return Collections.<ConceptEditor>singletonList(new ModesOfTransportation_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x3c32a02796cf0f46L, "RatingRulesLanguage.structure.MultiplyNLOperator"))) {
        return Collections.<ConceptEditor>singletonList(new MultiplyNLOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db57331L, "RatingRulesLanguage.structure.MultiplyOperator"))) {
        return Collections.<ConceptEditor>singletonList(new MultiplyOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2d9f2e13L, "RatingRulesLanguage.structure.NameIDPairTypedVarDeclaration"))) {
        return Collections.<ConceptEditor>singletonList(new NameIDPairTypedVarDeclaration_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x1b499c0ca9c50b12L, "RatingRulesLanguage.structure.Not"))) {
        return Collections.<ConceptEditor>singletonList(new Not_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x59a528db6b519f64L, "RatingRulesLanguage.structure.NumericVarType"))) {
        return Collections.<ConceptEditor>singletonList(new NumericVarType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x1b499c0ca9c50b11L, "RatingRulesLanguage.structure.Or"))) {
        return Collections.<ConceptEditor>singletonList(new Or_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x7627b8e69aa61093L, "RatingRulesLanguage.structure.OrNL"))) {
        return Collections.<ConceptEditor>singletonList(new OrNL_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x7627b8e69aa3a6aaL, "RatingRulesLanguage.structure.ParenthisizedExpression"))) {
        return Collections.<ConceptEditor>singletonList(new ParenthisizedExpression_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x3c32a02796cee0ecL, "RatingRulesLanguage.structure.PlusNLOperator"))) {
        return Collections.<ConceptEditor>singletonList(new PlusNLOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db57330L, "RatingRulesLanguage.structure.PlusOperator"))) {
        return Collections.<ConceptEditor>singletonList(new PlusOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db57cacL, "RatingRulesLanguage.structure.PointToPointDataDefinitoinBlock"))) {
        return Collections.<ConceptEditor>singletonList(new PointToPointDataDefinitoinBlock_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x59a528db6b519f65L, "RatingRulesLanguage.structure.PointToPointDataType"))) {
        return Collections.<ConceptEditor>singletonList(new PointToPointDataType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x59a528db6b5188dcL, "RatingRulesLanguage.structure.PointToPointFareMatrixVarType"))) {
        return Collections.<ConceptEditor>singletonList(new PointToPointFareMatrixVarType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db57332L, "RatingRulesLanguage.structure.PontToPointFarePriceFuction"))) {
        return Collections.<ConceptEditor>singletonList(new PontToPointFarePriceFuction_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x6773d363de92970aL, "RatingRulesLanguage.structure.ProductAttributes"))) {
        return Collections.<ConceptEditor>singletonList(new ProductAttributes_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2db09a76L, "RatingRulesLanguage.structure.ProductFamilyDeclaration"))) {
        return Collections.<ConceptEditor>singletonList(new ProductFamilyDeclaration_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x28b62f6a4da65550L, "RatingRulesLanguage.structure.ProductFamilyType"))) {
        return Collections.<ConceptEditor>singletonList(new ProductFamilyType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x6773d363de92970fL, "RatingRulesLanguage.structure.ProductInstanceAttributes"))) {
        return Collections.<ConceptEditor>singletonList(new ProductInstanceAttributes_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x7627b8e69aab741bL, "RatingRulesLanguage.structure.ProductSelectionCriteriaDef"))) {
        return Collections.<ConceptEditor>singletonList(new ProductSelectionCriteriaDef_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x7627b8e69aab7477L, "RatingRulesLanguage.structure.ProductSelectionCriterias"))) {
        return Collections.<ConceptEditor>singletonList(new ProductSelectionCriterias_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x28b62f6a4da4616eL, "RatingRulesLanguage.structure.ProductType"))) {
        return Collections.<ConceptEditor>singletonList(new ProductType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2db612d2L, "RatingRulesLanguage.structure.ProductsDefinitionBlock"))) {
        return Collections.<ConceptEditor>singletonList(new ProductsDefinitionBlock_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db56f54L, "RatingRulesLanguage.structure.RValue"))) {
        return Collections.<ConceptEditor>singletonList(new RValue_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da5a88fL, "RatingRulesLanguage.structure.RecurrenceCriteriaDef"))) {
        return Collections.<ConceptEditor>singletonList(new RecurrenceCriteriaDef_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da5e284L, "RatingRulesLanguage.structure.RecurrencesCriterias"))) {
        return Collections.<ConceptEditor>singletonList(new RecurrencesCriterias_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x318d55e0b578519fL, "RatingRulesLanguage.structure.RefConcessionCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new RefConcessionCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db56fe7L, "RatingRulesLanguage.structure.RefLocationGroupCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new RefLocationGroupCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db56fe8L, "RatingRulesLanguage.structure.RefProductSelectionCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new RefProductSelectionCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db56feaL, "RatingRulesLanguage.structure.RefRecurrenceCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new RefRecurrenceCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db57180L, "RatingRulesLanguage.structure.RefTransferAgreementSelectionCriteria"))) {
        return Collections.<ConceptEditor>singletonList(new RefTransferAgreementSelectionCriteria_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db71239L, "RatingRulesLanguage.structure.ReturnOperator"))) {
        return Collections.<ConceptEditor>singletonList(new ReturnOperator_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da4e212L, "RatingRulesLanguage.structure.RouteReference"))) {
        return Collections.<ConceptEditor>singletonList(new RouteReference_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x4be494590ea30640L, "RatingRulesLanguage.structure.RouteType"))) {
        return Collections.<ConceptEditor>singletonList(new RouteType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da4e231L, "RatingRulesLanguage.structure.Routes"))) {
        return Collections.<ConceptEditor>singletonList(new Routes_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2d9f2dc0L, "RatingRulesLanguage.structure.RulesEngineScript"))) {
        return Collections.<ConceptEditor>singletonList(new RulesEngineScript_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da13f8bL, "RatingRulesLanguage.structure.SPReference"))) {
        return Collections.<ConceptEditor>singletonList(new SPReference_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x4be494590ea306b9L, "RatingRulesLanguage.structure.ServiceProviderType"))) {
        return Collections.<ConceptEditor>singletonList(new ServiceProviderType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2d9f2dfdL, "RatingRulesLanguage.structure.ServiceProviders"))) {
        return Collections.<ConceptEditor>singletonList(new ServiceProviders_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db70f87L, "RatingRulesLanguage.structure.TierRounding"))) {
        return Collections.<ConceptEditor>singletonList(new TierRounding_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da5a5b6L, "RatingRulesLanguage.structure.TimeInterval"))) {
        return Collections.<ConceptEditor>singletonList(new TimeInterval_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da5a615L, "RatingRulesLanguage.structure.TimeIntervals"))) {
        return Collections.<ConceptEditor>singletonList(new TimeIntervals_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2d9f2dfaL, "RatingRulesLanguage.structure.TopologyDefinitionBlock"))) {
        return Collections.<ConceptEditor>singletonList(new TopologyDefinitionBlock_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x318d55e0b57850fdL, "RatingRulesLanguage.structure.TransferAgreementSelectionCriteriaDef"))) {
        return Collections.<ConceptEditor>singletonList(new TransferAgreementSelectionCriteriaDef_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db43fecL, "RatingRulesLanguage.structure.TransferAgreementSelectionCriterias"))) {
        return Collections.<ConceptEditor>singletonList(new TransferAgreementSelectionCriterias_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x30491a7e2ae06c3eL, "RatingRulesLanguage.structure.UDCReference"))) {
        return Collections.<ConceptEditor>singletonList(new UDCReference_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x30491a7e2ade5d01L, "RatingRulesLanguage.structure.UDFReference"))) {
        return Collections.<ConceptEditor>singletonList(new UDFReference_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db71989L, "RatingRulesLanguage.structure.UDTFunctionsDefinitionBlock"))) {
        return Collections.<ConceptEditor>singletonList(new UDTFunctionsDefinitionBlock_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2db612fdL, "RatingRulesLanguage.structure.UserDefinedCriteriasBlock"))) {
        return Collections.<ConceptEditor>singletonList(new UserDefinedCriteriasBlock_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x6773d363de8e8fe0L, "RatingRulesLanguage.structure.UsesConcept"))) {
        return Collections.<ConceptEditor>singletonList(new UsesConcept_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da5a58cL, "RatingRulesLanguage.structure.WeekDay"))) {
        return Collections.<ConceptEditor>singletonList(new WeekDay_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da55054L, "RatingRulesLanguage.structure.WeeklyOccurencePattern"))) {
        return Collections.<ConceptEditor>singletonList(new WeeklyOccurencePattern_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2daf1794L, "RatingRulesLanguage.structure.YearlyDateOccurencePattern"))) {
        return Collections.<ConceptEditor>singletonList(new YearlyDateOccurencePattern_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2daf14a8L, "RatingRulesLanguage.structure.YearlyOccurrencePattern"))) {
        return Collections.<ConceptEditor>singletonList(new YearlyOccurrencePattern_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
