package RatingRulesLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.nodeEditor.MPSFonts;
import jetbrains.mps.nodeEditor.BlockCells;
import jetbrains.mps.nodeEditor.cells.EditorCell_Indent;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class FareRule_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_dptif5_a(editorContext, node);
  }
  private EditorCell createCollection_dptif5_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_dptif5_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createCollection_dptif5_a0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_dptif5_b0(editorContext, node));
    return editorCell;
  }
  private EditorCell createCollection_dptif5_a0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_dptif5_a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_dptif5_a0a(editorContext, node));
    editorCell.addEditorCell(this.createComponent_dptif5_b0a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_dptif5_c0a(editorContext, node));
    editorCell.addEditorCell(this.createProperty_dptif5_d0a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_dptif5_e0a(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_dptif5_a0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Define");
    editorCell.setCellId("Constant_dptif5_a0a");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createComponent_dptif5_b0a(EditorContext editorContext, SNode node) {
    EditorCell editorCell = editorContext.getCellFactory().createEditorComponentCell(node, "jetbrains.mps.lang.core.editor.alias");
    Style style = new StyleImpl();
    ConstantsStyle_StyleSheet.apply_MyUDTEntityDefinition(style, editorCell);
    editorCell.getStyle().putAll(style);
    return editorCell;
  }
  private EditorCell createConstant_dptif5_c0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "\"");
    editorCell.setCellId("Constant_dptif5_c0a");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_dptif5_d0a(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("name");
    provider.setNoTargetText("<no name>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_name");
    Style style = new StyleImpl();
    ConstantsStyle_StyleSheet.apply_MyUDTEntityName(style, editorCell);
    editorCell.getStyle().putAll(style);
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_dptif5_e0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "\"");
    editorCell.setCellId("Constant_dptif5_e0a");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createCollection_dptif5_b0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_dptif5_b0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createCollection_dptif5_a1a(editorContext, node));
    editorCell.addEditorCell(this.createCollection_dptif5_b1a(editorContext, node));
    if (renderingCondition_dptif5_a2b0(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_dptif5_c1a(editorContext, node));
    }
    return editorCell;
  }
  private EditorCell createCollection_dptif5_a1a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_dptif5_a1a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    if (renderingCondition_dptif5_a0a1a(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_dptif5_a0b0(editorContext, node));
    }
    return editorCell;
  }
  private EditorCell createConstant_dptif5_a0b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "{");
    editorCell.setCellId("Constant_dptif5_a0b0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, 0, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, 0, true);
    style.set(StyleAttributes.FONT_STYLE, 0, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private static boolean renderingCondition_dptif5_a0a1a(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }
  private EditorCell createCollection_dptif5_b1a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_dptif5_b1a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createIndentCell_dptif5_a1b0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_dptif5_b1b0(editorContext, node));
    return editorCell;
  }
  private EditorCell createIndentCell_dptif5_a1b0(EditorContext editorContext, SNode node) {
    EditorCell_Indent editorCell = new EditorCell_Indent(editorContext, node);
    return editorCell;
  }
  private EditorCell createCollection_dptif5_b1b0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_dptif5_b1b0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setFoldable(true);
    editorCell.addEditorCell(this.createCollection_dptif5_a1b1a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_dptif5_b1b1a(editorContext, node));
    editorCell.addEditorCell(this.createCollection_dptif5_c1b1a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_dptif5_d1b1a(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_dptif5_e1b1a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_dptif5_f1b1a(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_dptif5_g1b1a(editorContext, node));
    return editorCell;
  }
  private EditorCell createCollection_dptif5_a1b1a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_dptif5_a1b1a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_dptif5_a0b1b0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_dptif5_b0b1b0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_dptif5_a0b1b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Precedence =");
    editorCell.setCellId("Constant_dptif5_a0b1b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_dptif5_b0b1b0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("precedence");
    provider.setNoTargetText("<no precedence>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_precedence");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_dptif5_b1b1a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_dptif5_b1b1a");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createCollection_dptif5_c1b1a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_dptif5_c1b1a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createCollection_dptif5_a2b1b0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_dptif5_b2b1b0(editorContext, node));
    if (renderingCondition_dptif5_a2c1b1a(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_dptif5_c2b1b0(editorContext, node));
    }
    return editorCell;
  }
  private EditorCell createCollection_dptif5_a2b1b0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_dptif5_a2b1b0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_dptif5_a0c1b1a(editorContext, node));
    if (renderingCondition_dptif5_a1a2b1b0(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_dptif5_b0c1b1a(editorContext, node));
    }
    return editorCell;
  }
  private EditorCell createConstant_dptif5_a0c1b1a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "SelectionCriteria");
    editorCell.setCellId("Constant_dptif5_a0c1b1a");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_dptif5_b0c1b1a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "{");
    editorCell.setCellId("Constant_dptif5_b0c1b1a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, 0, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, 0, true);
    style.set(StyleAttributes.FONT_STYLE, 0, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private static boolean renderingCondition_dptif5_a1a2b1b0(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }
  private EditorCell createCollection_dptif5_b2b1b0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_dptif5_b2b1b0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createIndentCell_dptif5_a1c1b1a(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_dptif5_b1c1b1a(editorContext, node));
    return editorCell;
  }
  private EditorCell createIndentCell_dptif5_a1c1b1a(EditorContext editorContext, SNode node) {
    EditorCell_Indent editorCell = new EditorCell_Indent(editorContext, node);
    return editorCell;
  }
  private EditorCell createRefNode_dptif5_b1c1b1a(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new FareRule_Editor.CriteriaSingleRoleHandler_dptif5_b1c1b1a(node, MetaAdapterFactory.getContainmentLink(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x6773d363de94c3dbL, 0x65d53d0d8db56f4bL, "Criteria"), editorContext);
    return provider.createCell();
  }
  private class CriteriaSingleRoleHandler_dptif5_b1c1b1a extends SingleRoleCellProvider {
    public CriteriaSingleRoleHandler_dptif5_b1c1b1a(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      editorCell.setSubstituteInfo(new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext));
      if (editorCell.getRole() == null) {
        editorCell.setRole("Criteria");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = super.createEmptyCell();
      editorCell.setCellId("empty_Criteria");
      installCellInfo(null, editorCell);
      return editorCell;
    }
    protected String getNoTargetText() {
      return "<no Criteria>";
    }
  }
  private EditorCell createConstant_dptif5_c2b1b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "}");
    editorCell.setCellId("Constant_dptif5_c2b1b0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, 0, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, 0, true);
    style.set(StyleAttributes.FONT_STYLE, 0, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private static boolean renderingCondition_dptif5_a2c1b1a(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }
  private EditorCell createConstant_dptif5_d1b1a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_dptif5_d1b1a");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_dptif5_e1b1a(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new FareRule_Editor.ActionsSingleRoleHandler_dptif5_e1b1a(node, MetaAdapterFactory.getContainmentLink(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x6773d363de94c3dbL, 0x65d53d0d8db56f4dL, "Actions"), editorContext);
    return provider.createCell();
  }
  private class ActionsSingleRoleHandler_dptif5_e1b1a extends SingleRoleCellProvider {
    public ActionsSingleRoleHandler_dptif5_e1b1a(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      editorCell.setSubstituteInfo(new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext));
      if (editorCell.getRole() == null) {
        editorCell.setRole("Actions");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = super.createEmptyCell();
      editorCell.setCellId("empty_Actions");
      installCellInfo(null, editorCell);
      return editorCell;
    }
    protected String getNoTargetText() {
      return "<no Actions>";
    }
  }
  private EditorCell createConstant_dptif5_f1b1a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_dptif5_f1b1a");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_dptif5_g1b1a(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new FareRule_Editor.PricingFunctionSingleRoleHandler_dptif5_g1b1a(node, MetaAdapterFactory.getContainmentLink(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x6773d363de94c3dbL, 0x65d53d0d8db56f50L, "PricingFunction"), editorContext);
    return provider.createCell();
  }
  private class PricingFunctionSingleRoleHandler_dptif5_g1b1a extends SingleRoleCellProvider {
    public PricingFunctionSingleRoleHandler_dptif5_g1b1a(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      editorCell.setSubstituteInfo(new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext));
      if (editorCell.getRole() == null) {
        editorCell.setRole("PricingFunction");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = super.createEmptyCell();
      editorCell.setCellId("empty_PricingFunction");
      installCellInfo(null, editorCell);
      return editorCell;
    }
    protected String getNoTargetText() {
      return "<no PricingFunction>";
    }
  }
  private EditorCell createConstant_dptif5_c1a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "}");
    editorCell.setCellId("Constant_dptif5_c1a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, 0, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, 0, true);
    style.set(StyleAttributes.FONT_STYLE, 0, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private static boolean renderingCondition_dptif5_a2b0(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }
}
