package RatingRulesLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.baseLanguage.editor.BaseLanguageStyle_StyleSheet;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;

public class LimitedPassbackCheckCriteria_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_ednhkr_a(editorContext, node);
  }
  private EditorCell createCollection_ednhkr_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_ednhkr_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createComponent_ednhkr_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_ednhkr_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_ednhkr_c0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_ednhkr_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_ednhkr_e0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_ednhkr_f0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_ednhkr_g0(editorContext, node));
    return editorCell;
  }
  private EditorCell createComponent_ednhkr_a0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = editorContext.getCellFactory().createEditorComponentCell(node, "jetbrains.mps.lang.core.editor.alias");
    Style style = new StyleImpl();
    BaseLanguageStyle_StyleSheet.apply_KeyWord(style, editorCell);
    editorCell.getStyle().putAll(style);
    return editorCell;
  }
  private EditorCell createConstant_ednhkr_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "(");
    editorCell.setCellId("Constant_ednhkr_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_ednhkr_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "AllowedTaps :");
    editorCell.setCellId("Constant_ednhkr_c0");
    Style style = new StyleImpl();
    ConstantsStyle_StyleSheet.apply_MyFctParamName(style, editorCell);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_ednhkr_d0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("AllowedTaps");
    provider.setNoTargetText("<no AllowedTaps>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_AllowedTaps");
    Style style = new StyleImpl();
    ConstantsStyle_StyleSheet.apply_MyFctParamValue(style, editorCell);
    editorCell.getStyle().putAll(style);
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_ednhkr_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "TimeInterval :");
    editorCell.setCellId("Constant_ednhkr_e0");
    Style style = new StyleImpl();
    ConstantsStyle_StyleSheet.apply_MyFctParamName(style, editorCell);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_ednhkr_f0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("Duration");
    provider.setNoTargetText("<no Duration>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_Duration");
    Style style = new StyleImpl();
    ConstantsStyle_StyleSheet.apply_MyFctParamValue(style, editorCell);
    editorCell.getStyle().putAll(style);
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_ednhkr_g0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ")");
    editorCell.setCellId("Constant_ednhkr_g0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
