package RatingRulesLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.baseLanguage.editor.BaseLanguageStyle_StyleSheet;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.nodeEditor.MPSFonts;
import jetbrains.mps.nodeEditor.BlockCells;
import jetbrains.mps.nodeEditor.cells.EditorCell_Indent;
import jetbrains.mps.lang.editor.cellProviders.RefCellCellProvider;
import jetbrains.mps.nodeEditor.InlineCellProvider;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class LocationGroupCriteriaDef_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_7xvfrc_a(editorContext, node);
  }
  private EditorCell createCollection_7xvfrc_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_7xvfrc_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_7xvfrc_a0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_7xvfrc_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_7xvfrc_c0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_7xvfrc_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_7xvfrc_e0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_7xvfrc_f0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_7xvfrc_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Define");
    editorCell.setCellId("Constant_7xvfrc_a0");
    Style style = new StyleImpl();
    BaseLanguageStyle_StyleSheet.apply_KeyWord(style, editorCell);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createComponent_7xvfrc_b0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = editorContext.getCellFactory().createEditorComponentCell(node, "jetbrains.mps.lang.core.editor.alias");
    Style style = new StyleImpl();
    ConstantsStyle_StyleSheet.apply_MyUDTEntityDefinition(style, editorCell);
    editorCell.getStyle().putAll(style);
    return editorCell;
  }
  private EditorCell createConstant_7xvfrc_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "\"");
    editorCell.setCellId("Constant_7xvfrc_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_7xvfrc_d0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("name");
    provider.setNoTargetText("<no name>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_name");
    Style style = new StyleImpl();
    ConstantsStyle_StyleSheet.apply_MyUDTEntityName(style, editorCell);
    editorCell.getStyle().putAll(style);
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_7xvfrc_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "\"");
    editorCell.setCellId("Constant_7xvfrc_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createCollection_7xvfrc_f0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_7xvfrc_f0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    style.set(StyleAttributes.INDENT_LAYOUT_ON_NEW_LINE, 0, true);
    editorCell.getStyle().putAll(style);
    editorCell.setFoldable(true);
    editorCell.addEditorCell(this.createCollection_7xvfrc_a5a(editorContext, node));
    return editorCell;
  }
  private EditorCell createCollection_7xvfrc_a5a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_7xvfrc_a5a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createCollection_7xvfrc_a0f0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_7xvfrc_b0f0(editorContext, node));
    if (renderingCondition_7xvfrc_a2a5a(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_7xvfrc_c0f0(editorContext, node));
    }
    return editorCell;
  }
  private EditorCell createCollection_7xvfrc_a0f0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_7xvfrc_a0f0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    if (renderingCondition_7xvfrc_a0a0f0(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_7xvfrc_a0a5a(editorContext, node));
    }
    return editorCell;
  }
  private EditorCell createConstant_7xvfrc_a0a5a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "{");
    editorCell.setCellId("Constant_7xvfrc_a0a5a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, 0, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, 0, true);
    style.set(StyleAttributes.FONT_STYLE, 0, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private static boolean renderingCondition_7xvfrc_a0a0f0(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }
  private EditorCell createCollection_7xvfrc_b0f0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_7xvfrc_b0f0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createIndentCell_7xvfrc_a1a5a(editorContext, node));
    editorCell.addEditorCell(this.createCollection_7xvfrc_b1a5a(editorContext, node));
    return editorCell;
  }
  private EditorCell createIndentCell_7xvfrc_a1a5a(EditorContext editorContext, SNode node) {
    EditorCell_Indent editorCell = new EditorCell_Indent(editorContext, node);
    return editorCell;
  }
  private EditorCell createCollection_7xvfrc_b1a5a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_7xvfrc_b1a5a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createCollection_7xvfrc_a1b0f0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_7xvfrc_b1b0f0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_7xvfrc_c1b0f0(editorContext, node));
    return editorCell;
  }
  private EditorCell createCollection_7xvfrc_a1b0f0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_7xvfrc_a1b0f0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_7xvfrc_a0b1a5a(editorContext, node));
    editorCell.addEditorCell(this.createRefCell_7xvfrc_b0b1a5a(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_7xvfrc_a0b1a5a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "OwnerSP =");
    editorCell.setCellId("Constant_7xvfrc_a0b1a5a");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefCell_7xvfrc_b0b1a5a(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new RefCellCellProvider(node, editorContext);
    provider.setRole("ownerSP");
    provider.setNoTargetText("<no ownerSP>");
    EditorCell editorCell;
    provider.setAuxiliaryCellProvider(new LocationGroupCriteriaDef_Editor._Inline_7xvfrc_a1a1b0f0());
    editorCell = provider.createEditorCell(editorContext);
    if (editorCell.getRole() == null) {
      editorCell.setReferenceCell(true);
      editorCell.setRole("ownerSP");
    }
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  public static class _Inline_7xvfrc_a1a1b0f0 extends InlineCellProvider {
    public _Inline_7xvfrc_a1a1b0f0() {
      super();
    }
    public EditorCell createEditorCell(EditorContext editorContext) {
      return this.createEditorCell(editorContext, this.getSNode());
    }
    public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
      return this.createProperty_7xvfrc_a0b0b1a5a(editorContext, node);
    }
    private EditorCell createProperty_7xvfrc_a0b0b1a5a(EditorContext editorContext, SNode node) {
      CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
      provider.setRole("name");
      provider.setNoTargetText("<no name>");
      provider.setReadOnly(true);
      EditorCell editorCell;
      editorCell = provider.createEditorCell(editorContext);
      editorCell.setCellId("property_name_1");
      Style style = new StyleImpl();
      ConstantsStyle_StyleSheet.apply_MyUDTEntityName(style, editorCell);
      editorCell.getStyle().putAll(style);
      editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
      SNode attributeConcept = provider.getRoleAttribute();
      Class attributeKind = provider.getRoleAttributeClass();
      if (attributeConcept != null) {
        EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
        return manager.createNodeRoleAttributeCell(attributeConcept, attributeKind, editorCell);
      } else
      return editorCell;
    }
  }
  private EditorCell createConstant_7xvfrc_b1b0f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_7xvfrc_b1b0f0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createCollection_7xvfrc_c1b0f0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_7xvfrc_c1b0f0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.setFoldable(true);
    editorCell.addEditorCell(this.createCollection_7xvfrc_a2b1a5a(editorContext, node));
    return editorCell;
  }
  private EditorCell createCollection_7xvfrc_a2b1a5a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_7xvfrc_a2b1a5a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createCollection_7xvfrc_a0c1b0f0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_7xvfrc_b0c1b0f0(editorContext, node));
    if (renderingCondition_7xvfrc_a2a2b1a5a(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_7xvfrc_c0c1b0f0(editorContext, node));
    }
    return editorCell;
  }
  private EditorCell createCollection_7xvfrc_a0c1b0f0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_7xvfrc_a0c1b0f0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createConstant_7xvfrc_a0a2b1a5a(editorContext, node));
    if (renderingCondition_7xvfrc_a1a0c1b0f0(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_7xvfrc_b0a2b1a5a(editorContext, node));
    }
    return editorCell;
  }
  private EditorCell createConstant_7xvfrc_a0a2b1a5a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Evaluates");
    editorCell.setCellId("Constant_7xvfrc_a0a2b1a5a");
    Style style = new StyleImpl();
    BaseLanguageStyle_StyleSheet.apply_KeyWord(style, editorCell);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_7xvfrc_b0a2b1a5a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "{");
    editorCell.setCellId("Constant_7xvfrc_b0a2b1a5a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, 0, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, 0, true);
    style.set(StyleAttributes.FONT_STYLE, 0, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private static boolean renderingCondition_7xvfrc_a1a0c1b0f0(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }
  private EditorCell createCollection_7xvfrc_b0c1b0f0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_7xvfrc_b0c1b0f0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, 0, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(this.createIndentCell_7xvfrc_a1a2b1a5a(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_7xvfrc_b1a2b1a5a(editorContext, node));
    return editorCell;
  }
  private EditorCell createIndentCell_7xvfrc_a1a2b1a5a(EditorContext editorContext, SNode node) {
    EditorCell_Indent editorCell = new EditorCell_Indent(editorContext, node);
    return editorCell;
  }
  private EditorCell createRefNode_7xvfrc_b1a2b1a5a(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new LocationGroupCriteriaDef_Editor.expressionSingleRoleHandler_7xvfrc_b1a2b1a5a(node, MetaAdapterFactory.getContainmentLink(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x318d55e0b57737f2L, 0x318d55e0b57737f5L, "expression"), editorContext);
    return provider.createCell();
  }
  private class expressionSingleRoleHandler_7xvfrc_b1a2b1a5a extends SingleRoleCellProvider {
    public expressionSingleRoleHandler_7xvfrc_b1a2b1a5a(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      editorCell.setSubstituteInfo(new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext));
      if (editorCell.getRole() == null) {
        editorCell.setRole("expression");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = super.createEmptyCell();
      editorCell.setCellId("empty_expression");
      installCellInfo(null, editorCell);
      return editorCell;
    }
    protected String getNoTargetText() {
      return "<no expression>";
    }
  }
  private EditorCell createConstant_7xvfrc_c0c1b0f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "}");
    editorCell.setCellId("Constant_7xvfrc_c0c1b0f0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, 0, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, 0, true);
    style.set(StyleAttributes.FONT_STYLE, 0, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private static boolean renderingCondition_7xvfrc_a2a2b1a5a(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }
  private EditorCell createConstant_7xvfrc_c0f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "}");
    editorCell.setCellId("Constant_7xvfrc_c0f0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.MATCHING_LABEL, 0, "brace");
    style.set(StyleAttributes.INDENT_LAYOUT_NO_WRAP, 0, true);
    style.set(StyleAttributes.FONT_STYLE, 0, MPSFonts.PLAIN);
    editorCell.getStyle().putAll(style);
    editorCell.setDefaultText("");
    return editorCell;
  }
  private static boolean renderingCondition_7xvfrc_a2a5a(SNode node, EditorContext editorContext) {
    return BlockCells.useBraces();
  }
}
