package RatingRulesLanguage.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class LogicalOperatorFactory {
  public static class NodeFactory_1966274290525733026 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      if (SNodeOperations.isInstanceOf(sampleNode, MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x1b499c0ca9c45ca1L, "RatingRulesLanguage.structure.LogicalOperator"))) {
        SLinkOperations.setTarget(newNode, MetaAdapterFactory.getContainmentLink(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x1b499c0ca9c45ca1L, 0x1b499c0ca9c45ca5L, "left"), SLinkOperations.getTarget(SNodeOperations.cast(sampleNode, MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x1b499c0ca9c45ca1L, "RatingRulesLanguage.structure.LogicalOperator")), MetaAdapterFactory.getContainmentLink(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x1b499c0ca9c45ca1L, 0x1b499c0ca9c45ca5L, "left")));
        SLinkOperations.setTarget(newNode, MetaAdapterFactory.getContainmentLink(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x1b499c0ca9c45ca1L, 0x1b499c0ca9c45ca8L, "right"), SLinkOperations.getTarget(SNodeOperations.cast(sampleNode, MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x1b499c0ca9c45ca1L, "RatingRulesLanguage.structure.LogicalOperator")), MetaAdapterFactory.getContainmentLink(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x1b499c0ca9c45ca1L, 0x1b499c0ca9c45ca8L, "right")));
      }
    }
  }
}
