package RatingRulesLanguage.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class RecurrenceCriteria_Factory {
  public static class NodeFactory_3570604503179829097 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      // Insert code to initialize ID node 
      if (SNodeOperations.isInstanceOf(enclosingNode, MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da5e284L, "RatingRulesLanguage.structure.RecurrencesCriterias"))) {
        SPropertyOperations.set(newNode, MetaAdapterFactory.getProperty(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x7627b8e69aa84759L, 0x7627b8e69aa8475aL, "ID"), "" + (ListSequence.fromList(SLinkOperations.getChildren(SNodeOperations.cast(enclosingNode, MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da5e284L, "RatingRulesLanguage.structure.RecurrencesCriterias")), MetaAdapterFactory.getContainmentLink(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x9a73ffb2da5e284L, 0x9a73ffb2da5e2a0L, "list"))).count()));
      }

    }
  }
}
