package RatingRulesLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.smodel.SNodePointer;

public class ConstantPointToPointFareMatrixValue_Constraints extends BaseConstraintsDescriptor {
  public ConstantPointToPointFareMatrixValue_Constraints() {
    super(MetaIdFactory.conceptId(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db57cabL));
  }
  @Override
  public boolean hasOwnCanBeChildMethod() {
    return true;
  }
  @Override
  public boolean canBeChild(@Nullable SNode node, SNode parentNode, SNode link, SNode childConcept, final IOperationContext operationContext, @Nullable final CheckingNodeContext checkingNodeContext) {
    boolean result = static_canBeAChild(node, parentNode, link, childConcept, operationContext);

    if (!(result) && checkingNodeContext != null) {
      checkingNodeContext.setBreakingNode(canBeChildBreakingPoint);
    }

    return result;
  }
  public static boolean static_canBeAChild(SNode node, SNode parentNode, SNode link, SNode childConcept, final IOperationContext operationContext) {
    return !((SNodeOperations.isInstanceOf(parentNode, MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db71239L, "RatingRulesLanguage.structure.ReturnOperator")) || SNodeOperations.isInstanceOf(parentNode, MetaAdapterFactory.getConcept(0xfffd25317c948b3L, 0x9419ce44b0a40631L, 0x65d53d0d8db57316L, "RatingRulesLanguage.structure.BaseOperator"))));
  }
  private static SNodePointer canBeChildBreakingPoint = new SNodePointer("r:a0818848-e2be-4df2-994d-f3775e032ff2(RatingRulesLanguage.constraints)", "7758302892021481535");
}
